# Generated by Django 5.0.6 on 2024-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_coffees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contein', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
