# Generated by Django 5.0.6 on 2024-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffees',
            name='IsIce',
            field=models.BooleanField(null=True),
        ),
    ]
